In [2]:
import numpy as np
import pandas as pd
import sklearn as sk 

In [3]:
dataset=pd.read_csv("https://raw.githubusercontent.com/uiuc-cse/data-fa14/gh-pages/data/iris.csv")

In [6]:
x=dataset.iloc[:,1:4].values

In [7]:
y=dataset.iloc[:,4].values

In [8]:
from sklearn.preprocessing import LabelEncoder

In [9]:
y=LabelEncoder().fit_transform(y)

In [10]:
from sklearn.model_selection import train_test_split

In [11]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2)

In [12]:
from sklearn.svm import SVC
classifier_svm_sigmoid=SVC(kernel='sigmoid')

In [13]:
classifier_svm_sigmoid.fit(x_train,y_train)

SVC(C=1.0, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='scale', kernel='sigmoid',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=False)

In [14]:
y_pred=classifier_svm_sigmoid.predict(x_test)
from sklearn.metrics import confusion_matrix
confusion_matrix(y_test,y_pred)

array([[ 5,  5,  0],
       [ 5,  3,  0],
       [11,  1,  0]], dtype=int64)

In [15]:
#trying the linear kernel

classifier_svm_linear=SVC(kernel='linear')
classifier_svm_linear.fit(x_train,y_train)

SVC(C=1.0, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='scale', kernel='linear',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=False)

In [16]:
y_pred=classifier_svm_linear.predict(x_test)
confusion_matrix(y_test,y_pred)

array([[10,  0,  0],
       [ 0,  7,  1],
       [ 0,  2, 10]], dtype=int64)

In [19]:
classifier_svm_rbf=SVC(kernel='rbf')
classifier_svm_rbf.fit(x_train,y_train)

SVC(C=1.0, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='scale', kernel='rbf',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=False)

In [20]:
y_pred=classifier_svm_rbf.predict(x_test)
confusion_matrix(y_test,y_pred)

array([[10,  0,  0],
       [ 0,  7,  1],
       [ 0,  2, 10]], dtype=int64)

In [21]:
#using polynomial kernel 
classifier_svm_poly=SVC(kernel="poly")
classifier_svm_poly.fit(x_train,y_train)


SVC(C=1.0, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='scale', kernel='poly',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=False)

In [22]:
y_pred=classifier_svm_poly.predict(x_test)
confusion_matrix(y_test,y_pred)

array([[10,  0,  0],
       [ 0,  7,  1],
       [ 0,  2, 10]], dtype=int64)